// ════════════════════════════════════════════════════════════════════════
// Parity test: the Dart engine must match the Python reference.
//
// Golden vectors are generated by gen_golden.py from physical_rank_engine.py.
// Layout expected:
//   lib/rank_engine.dart
//   test/rank_engine_test.dart      (this file)
//   test/golden_vectors.json
// Run with:  dart test   (or  flutter test)
// ════════════════════════════════════════════════════════════════════════
import 'dart:convert';
import 'dart:io';
import 'package:test/test.dart';
import 'package:physical/engine/rank_engine.dart';

double? _d(dynamic v) => v == null ? null : (v as num).toDouble();

void main() {
  final file = File('test/golden_vectors.json').existsSync()
      ? File('test/golden_vectors.json')
      : File('golden_vectors.json');
  final golden = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;

  // Tolerances absorb tiny erf / inverse-CDF approximation differences.
  const pTol = 0.05; // percentile & top_pct, in 0–100 units
  const rvTol = 0.005; // rank value
  const kgTol = 0.2; // derived threshold, kg

  group('metric cases', () {
    for (final raw in golden['metric_cases'] as List) {
      final c = raw as Map<String, dynamic>;
      final exp = c['expected'] as Map<String, dynamic>;
      final label =
          '${c['metric']} value=${c['value']} bw=${c['bodyweight']}';
      test(label, () {
        final r = tierOf(c['metric'] as String, _d(c['value'])!, _d(c['bodyweight']));
        expect(r.tier, exp['tier'], reason: 'tier ($label)');
        expect(r.sub, exp['sub'], reason: 'sub ($label)');
        expect(r.percentile, closeTo(exp['percentile'] as num, pTol),
            reason: 'percentile ($label)');
        expect(r.topPct, closeTo(exp['top_pct'] as num, pTol),
            reason: 'top_pct ($label)');
        expect(r.rankValue, closeTo(exp['rank_value'] as num, rvTol),
            reason: 'rank_value ($label)');
      });
    }
  });

  group('threshold cases (derived, never typed)', () {
    for (final raw in golden['threshold_cases'] as List) {
      final c = raw as Map<String, dynamic>;
      final label = '${c['metric']} ${c['tier']} bw=${c['bodyweight']}';
      test(label, () {
        final kg =
            threshold(c['metric'] as String, c['tier'] as String, _d(c['bodyweight']));
        expect(kg, closeTo(c['expected_kg'] as num, kgTol), reason: label);
      });
    }
  });

  group('body fat health-target (hockey-stick)', () {
    test('≤12% all hit Glory; leaner never out-ranks the ideal', () {
      final r12 = tierOf('body_fat_pct', 12);
      final r6 = tierOf('body_fat_pct', 6);
      expect(r12.tier, 'Glory');
      expect(r6.tier, 'Glory');
      expect(r6.rankValue, closeTo(r12.rankValue, 1e-9)); // 6% is no "better" than 12%
    });
    test('rank decreases monotonically as body fat rises above the ideal', () {
      const vals = [12.0, 13.0, 14.0, 16.0, 20.0, 25.0, 30.0];
      for (var i = 1; i < vals.length; i++) {
        expect(rankValue('body_fat_pct', vals[i]) <= rankValue('body_fat_pct', vals[i - 1]),
            isTrue, reason: '${vals[i]}% should rank ≤ ${vals[i - 1]}%');
      }
    });
  });

  group('overall by category (equal-weight blend)', () {
    var i = 0;
    for (final raw in (golden['category_overall_cases'] as List? ?? const [])) {
      final c = raw as Map<String, dynamic>;
      final exp = c['expected'] as Map<String, dynamic>;
      test('category overall #${i++}', () {
        final byCat = <String, List<Log>>{};
        (c['logs_by_cat'] as Map<String, dynamic>).forEach((cat, list) {
          byCat[cat] = [
            for (final d in (list as List))
              Log((d as Map)['metric'] as String, _d(d['value'])!, bodyweight: _d(d['bodyweight']))
          ];
        });
        final r = overallByCategory(byCat);
        expect(r.tier, exp['tier']);
        expect(r.sub, exp['sub']);
        expect(r.topPct, closeTo(exp['top_pct'] as num, pTol));
        expect(r.rankValue, closeTo(exp['rank_value'] as num, rvTol));
      });
    }
  });

  group('overall (z-space blend)', () {
    var i = 0;
    for (final raw in golden['overall_cases'] as List) {
      final c = raw as Map<String, dynamic>;
      final exp = c['expected'] as Map<String, dynamic>;
      test('overall #${i++}', () {
        final logs = (c['logs'] as List).map((d) {
          final m = d as Map<String, dynamic>;
          return Log(m['metric'] as String, _d(m['value'])!,
              bodyweight: _d(m['bodyweight']));
        }).toList();
        final r = overall(logs);
        expect(r.tier, exp['tier']);
        expect(r.sub, exp['sub']);
        expect(r.topPct, closeTo(exp['top_pct'] as num, pTol));
        expect(r.rankValue, closeTo(exp['rank_value'] as num, rvTol));
      });
    }
  });
}
